"""add unique to login

Revision ID: 37935b69a7ed
Revises: 7063d066a84e
Create Date: 2025-08-03 09:55:53.048460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37935b69a7ed'
down_revision: Union[str, Sequence[str], None] = '7063d066a84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=False)
    # ### end Alembic commands ###
